export const salas = [
  {
    id: 1,
    status: "LIVRE",
    sala: "SmartLab",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 2,
    status: "LIVRE",
    sala: "Sala 02",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 3,
    status: "EM_MANUTENCAO",
    sala: "Sala 03",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 4,
    status: "RESERVADA",
    sala: "Sala 04",
    localizacao: "PRIMEIRO_ANDAR",
    reservas: [
      {
        id: "r3",
        tipo: "DISCIPLINA",
        nomeDisciplina: "Banco de Dados",
        professor: "Professor",
        horario: "Seg–Qua (08h–10h)",
      },
    ],
  },
  {
    id: 5,
    status: "EM_MANUTENCAO",
    sala: "Lab de Usabilidade",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 6,
    status: "LIVRE",
    sala: "C.A",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 7,
    status: "RESERVADA",
    sala: "Sala 01",
    localizacao: "PRIMEIRO_ANDAR",
    reservas: [
      {
        id: "r7",
        tipo: "DISCIPLINA",
        nomeDisciplina: "Programação Web",
        professor: "Professor",
        horario: "Seg–Qua (08h–10h)",
      },
    ],
  },
  {
    id: 8,
    status: "LIVRE",
    sala: "Atelier",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 9,
    status: "LIVRE",
    sala: "Sala 05",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 10,
    status: "LIVRE",
    sala: "Lab de Tecnodocência",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 11,
    status: "LIVRE",
    sala: "Lab de Audiovisual",
    localizacao: "PRIMEIRO_ANDAR",
  },
  {
    id: 12,
    status: "LIVRE",
    sala: "Lab 01",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 13,
    status: "LIVRE",
    sala: "Lab 02",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 14,
    status: "LIVRE",
    sala: "Lab 03",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 15,
    status: "EM_MANUTENCAO",
    sala: "Laboratório de Jogos",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 16,
    status: "RESERVADA",
    sala: "Laboratório de computação fisica",
    localizacao: "SEGUNDO_ANDAR",
    reservas: [
      {
        id: "r16",
        tipo: "DISCIPLINA",
        nomeDisciplina: "Computação Física",
        professor: "Professora",
        horario: "Ter–Qui (14h–16h)",
      },
    ],
  },
  {
    id: 17,
    status: "LIVRE",
    sala: "Lab 04",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 18,
    status: "LIVRE",
    sala: "Lab 05",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 19,
    status: "EM_MANUTENCAO",
    sala: "Lab 06",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 20,
    status: "RESERVADA",
    sala: "Laboratório de sistemas",
    localizacao: "SEGUNDO_ANDAR",
    reservas: [
      {
        id: "r20",
        tipo: "DISCIPLINA",
        nomeDisciplina: "Sistemas Distribuídos",
        professor: "Prof. Ana",
        horario: "Seg (10h–12h)",
      },
    ],
  },
  {
    id: 21,
    status: "LIVRE",
    sala: "Lab P&D",
    localizacao: "SEGUNDO_ANDAR",
  },
  {
    id: 22,
    status: "LIVRE",
    sala: "Lab P&D",
    localizacao: "SEGUNDO_ANDAR",
  },
];
